In [16]:
import pandas as pd

# Import classifier and create object
from ethnos_classifier import EthnosClassifier

clf = EthnosClassifier()

c:\Users\Robert_Beta\miniforge3\envs\epp\Lib\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator TfidfTransformer from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Robert_Beta\miniforge3\envs\epp\Lib\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator TfidfVectorizer from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Robert_Beta\miniforge3\envs\epp\Lib\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator SGDClassifier from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Robert_Beta\miniforge3\envs\epp\Lib\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Robert_Beta\miniforge3\envs\epp\Lib\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [25]:
# Predict classes for "example.csv" table and save results to "example_pred.csv"
clf.predict('../data/names.csv', 'names_pred.csv')

c:\Users\Robert_Beta\.vscode\projects\Thesis\ruEthnicNamesPublic\mlPipeline\ethnos_classifier.py:65: UserWarning: Warning: Some names in your data contain characters different from russian letters, "-" character or space. Results for this names will be "INVALID" or 0.0 for probabilities
  df = pd.read_csv(csv_path)

In [26]:
pd.read_csv('names_pred.csv')

       first_name    last_name       ethnos   agr_ethnos
0         Николай     Железняк   Belarusian    BelRusUkr
1       Александр        Бегин      Russian    BelRusUkr
2          Михаил  Пономаренко      Russian    BelRusUkr
3        Владимир    Балабанов      Russian    BelRusUkr
4        Владимир     Высоцкий      Russian    BelRusUkr
...           ...          ...          ...          ...
119149     Шахмар    Мустафаев    Dagestani    CheDagIng
119150     Виктор     Кокшаров      Russian    BelRusUkr
119151       Пётр    Урбанович   Belarusian    BelRusUkr
119152     Эльвин     Гусейнов  Azerbaijani  Azerbaijani
119153      Орхан     Рустамов  Azerbaijani  Azerbaijani

[119154 rows x 4 columns]

In [7]:
pd.read_csv('example_pr_pred.csv')

,first_name,last_name,Armenian_full,Azerbaijani_full,Bashkir_full,Belarusian_full,Buryat_full,Chechen_full,Dagestani_full,Georgian_full,...,CheDagIng_agr,Georgian_agr,Jewish_agr,KabAdKarBalOs_agr,Kalmyk_agr,KazKyr_agr,Moldovan_agr,TajUzb_agr,Tuvan_agr,Yakut_agr
0,Рая,Левтеева,0.0,0.000000,0.000000,0.065640,0.000000,0.109032,0.000000,0.0,...,0.115744,0.0,0.0,0.186899,0.131571,0.0,0.000000,0.0,0.0,0.0
1,Даниил,Леснухин,0.0,0.000000,0.041079,0.299385,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
2,Айгулька,Гильмуллина,0.0,0.000000,0.461893,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
3,Евгения,Котова,0.0,0.000000,0.000000,0.329080,0.011477,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
4,Максим,Ефремов,0.0,0.000000,0.000000,0.098288,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Маргарита,Петрова,0.0,0.000000,0.000000,0.223224,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
1996,Дмитрий,Гречищев,0.0,0.000000,0.000000,0.149228,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
1997,Андрий,Соколов,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
1998,Эльшад,Алиев,0.0,0.568518,0.000000,0.000000,0.000000,0.000000,0.391302,0.0,...,0.296676,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0
1999,Анастасия,Лёвочкина,0.0,0.000000,0.000000,0.676288,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.116329,0.0,0.0,0.0